In [13]:
import pandas as pd
import numpy as np
from scipy import stats
from pydataset import data

1) Answer with the type of stats test you would use (assume normal distribution):
    a) Do students get better test grades if they have a rubber duck on their desk?
        - single sample T-test with one tail
    
    b)Does smoking affect when (whether) or not someone has lung cancer?
        - discreet vs discreet; chi-squared test
    
    c)Is gender independent of a person’s blood type?
        - ANOVA 
    
    d)A farming company wants to know if a new fertilizer has improved crop yield or not
        - single sample, single tail T-test
    
    e)Does the length of time of the lecture correlate with a students grade?
        - two sample correlation test
    
    f)Do people with dogs live in apartments more than people with cats?
        - single sample t test

#### 2) Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.

In [7]:
computer_breakdown =  pd.DataFrame(np.array([[49, 20],[1,30]]),columns=['CodeUp','not_CodeUp'], index=['Mac_le_More','Mac_le_Less'])

In [8]:
computer_breakdown

CodeUp  not_CodeUp
Mac_le_More      49          20
Mac_le_Less       1          30

In [11]:
chi2, p, degf, expected = stats.chi2_contingency(computer_breakdown)

In [12]:
print('Observed')
print(computer_breakdown.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed
[[49 20]
 [ 1 30]]

Expected
[[34 34]
 [15 15]]

----
chi^2 = 36.6526
p     = 0.0000


### from this, we can conlude there is a strong correlation between students being in codeup and having a mac computer


#### 3) Choose another 2 categorical variables from the mpg dataset and perform a chi^2 contingency table test with them. Be sure to state your null and alternative hypotheses.

In [15]:
mpg = data('mpg')

In [16]:
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [18]:
mpg.nunique()

manufacturer    15
model           38
displ           35
year             2
cyl              4
trans           10
drv              3
cty             21
hwy             27
fl               5
class            7
dtype: int64

In [19]:
# drive options vs. year made will result in a 2x3 contingency table
# drive options: front, rear, all
# year options: 1999, 2008

### hypotheses: 
$H_0$: there is no correlation between the year a car was made and the type of drive it has
\
$H_A$: there is a correlation between the year a car was made and the type of drive it has

In [21]:
observed = pd.crosstab(mpg.year, mpg.drv)
observed

drv    4   f   r
year            
1999  49  57  11
2008  54  49  14

In [22]:
chi2, p, degf, expected = stats.chi2_contingency(observed)


In [23]:
print('Observed')
print(observed.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed
[[49 57 11]
 [54 49 14]]

Expected
[[51 53 12]
 [51 53 12]]

----
chi^2 = 1.2065
p     = 0.5470
