In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%config InlineBackend.figure_format = 'retina'
import viz # curriculum example visualizations

np.random.seed(38)

In [7]:
#How likely is it that you roll doubles when rolling two dice?
# Assumptions: I roll two dice simultaneously, what is the likelyhood they are the same?
# NOT: roll die A, what is the likelyhood die B matches?
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], size = (n_trials, n_dice))
rolls

array([[2, 4],
       [6, 4],
       [5, 5],
       ...,
       [2, 6],
       [5, 5],
       [5, 3]])

In [8]:
rolls_df = pd.DataFrame(rolls, columns=['roll_1', 'roll_2',])
rolls_df.head()

roll_1  roll_2
0       2       4
1       6       4
2       5       5
3       3       2
4       2       5

In [9]:
doubles = rolls_df.roll_1 == rolls_df.roll_2
doubles

0       False
1       False
2        True
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998     True
9999    False
Length: 10000, dtype: bool

In [10]:
sum(doubles)

1623

In [12]:
# percent chance of rolling doubles
sum(doubles)/len(rolls) * 100

16.23

In [29]:
#2a If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# NOT three in a row. 
# 3 heads, no more, no less
n_trials = nrows = 10_000
n_coins = ncols = 8

flips = np.random.choice([True, False], size = (n_trials, n_coins))
flips

#heads = True
# tails = False

array([[False,  True,  True, ..., False, False,  True],
       [False,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ..., False,  True,  True],
       ...,
       [ True,  True, False, ..., False,  True, False],
       [False,  True, False, ...,  True, False, False],
       [ True,  True, False, ...,  True,  True, False]])

In [30]:
flips_df = pd.DataFrame(flips, columns=['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8'])
flips_df.head()

f1     f2     f3     f4     f5     f6     f7     f8
0  False   True   True   True  False  False  False   True
1  False   True   True  False   True  False   True   True
2   True   True   True  False   True  False   True   True
3  False  False   True   True   True   True  False   True
4   True   True  False  False   True  False   True  False

In [38]:
(flips_df.sum(axis = 1) == 3).mean()

0.2184

In [37]:
#more than 3 heads
(flips_df.sum(axis = 1) > 3).mean()

0.6356

In [39]:
# less than 3 heads (just to check my work and make sure they add up to 1.0)
(flips_df.sum(axis = 1) < 3).mean()

0.146

In [40]:
# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.
#    (W-W-W-D)
#    Assuming that Codeup randomly selects an alumni to put on a billboard, 
#    what are the odds that the two billboards I drive past both have data science students on them?


p_ds_students = .25
n_billboards = ncols = 2
n_simulated_students = nrows = 10**3

In [41]:
data = np.random.random(size =(nrows, ncols))
data

array([[0.11072028, 0.17327876],
       [0.1026073 , 0.52852152],
       [0.15078434, 0.80161212],
       ...,
       [0.8008715 , 0.06148492],
       [0.12364835, 0.2721015 ],
       [0.90367747, 0.82423612]])

In [43]:
both_ds_students = data < p_ds_students
both_ds_students

array([[ True,  True],
       [ True, False],
       [ True, False],
       ...,
       [False,  True],
       [ True, False],
       [False, False]])

In [45]:
(both_ds_students.sum(axis=1) == 2).mean()

0.072

In [54]:
# 4 Poptart Problem
# Monday morning = 17 poptarts. Averge consumption rate: 3/day. STD: 1.5 
# Mon EOD: 14
# Tues EOD: 11
# Wed EOD: 8
# Thu EOD: 5
# Fri EOD: 2 what is the liklihood one of them will be mine?

poptarts = np.random.normal(3, 1.5, size=(10, 5))
poptarts_df = pd.DataFrame(poptarts, columns = ['M', 'T', 'W', 'Th', 'F'])
poptarts_df

M         T         W        Th         F
0  2.754663  3.305781  5.075428  3.355585  0.360560
1  3.357916  4.749546  1.256678  4.407390  2.317589
2  3.132745  4.691988  2.716303  2.473361  1.542024
3  4.495986  3.476576  2.673707  3.377083  4.000160
4  4.798414  4.727976  3.864261  1.501108  3.783632
5  2.123491  3.372824  2.756316  3.955875  4.631400
6  2.377617  5.290105  2.648585  4.876278  5.323677
7  2.621638  1.305784  2.556778  3.168505  2.631591
8  2.987118  3.123210  3.316638 -0.507865  4.484271
9  2.144857  2.891502  2.818165  2.003391  2.856540

In [55]:
# if the sum of a row >= 17, I get no poptarts on Friday. 30% chance I don't get poptarts.
(poptarts_df.sum(axis = 1) >=17).mean()

0.3

In [56]:
(poptarts_df.sum(axis = 1) <=17).mean()

0.7

In [87]:
#5. Compare heights:
#.  - Men have an average height of 178 cm and standard deviation of 8cm.
#.  - Women have a mean of 170, sd = 6cm.
#.  _ If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

men = np.random.normal(178, 8, (100))
women = np.random.normal(170, 6, (100))
men_df = pd.DataFrame(men, columns = ["men"])
women_df = pd.DataFrame(women, columns = ["women"])

In [88]:
men_df

men
0   174.820053
1   184.833461
2   182.050676
3   182.649470
4   176.800016
..         ...
95  178.969282
96  180.530786
97  175.822883
98  174.996737
99  184.417338

[100 rows x 1 columns]

In [89]:
women_df

women
0   161.381920
1   160.029094
2   173.683999
3   174.274000
4   161.156121
..         ...
95  174.957996
96  159.160203
97  174.281224
98  162.014317
99  177.210948

[100 rows x 1 columns]

In [90]:
heights_df = pd.concat([men_df, women_df], axis = 1)
heights_df

men       women
0   174.820053  161.381920
1   184.833461  160.029094
2   182.050676  173.683999
3   182.649470  174.274000
4   176.800016  161.156121
..         ...         ...
95  178.969282  174.957996
96  180.530786  159.160203
97  175.822883  174.281224
98  174.996737  162.014317
99  184.417338  177.210948

[100 rows x 2 columns]

In [91]:
heights_df.men.max()

193.15936894624448

In [100]:
heights_df['tall_women']= heights_df.men < heights_df.women


In [101]:
heights_df

men       women  tall_women
0   174.820053  161.381920       False
1   184.833461  160.029094       False
2   182.050676  173.683999       False
3   182.649470  174.274000       False
4   176.800016  161.156121       False
..         ...         ...         ...
95  178.969282  174.957996       False
96  180.530786  159.160203       False
97  175.822883  174.281224       False
98  174.996737  162.014317       False
99  184.417338  177.210948       False

[100 rows x 3 columns]

In [104]:
heights_df.tall_women.sum()

12