In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%config InlineBackend.figure_format = 'retina'
import viz # curriculum example visualizations

np.random.seed(38)

In [3]:
#How likely is it that you roll doubles when rolling two dice?
# Assumptions: I roll two dice simultaneously, what is the likelyhood they are the same?
# NOT: roll die A, what is the likelyhood die B matches?
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], size = (n_trials, n_dice))
rolls

array([[2, 4],
       [6, 4],
       [5, 5],
       ...,
       [2, 6],
       [5, 5],
       [5, 3]])

In [4]:
rolls_df = pd.DataFrame(rolls, columns=['roll_1', 'roll_2',])
rolls_df.head()

roll_1  roll_2
0       2       4
1       6       4
2       5       5
3       3       2
4       2       5

In [5]:
doubles = rolls_df.roll_1 == rolls_df.roll_2
doubles

0       False
1       False
2        True
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998     True
9999    False
Length: 10000, dtype: bool

In [6]:
sum(doubles)

1623

In [7]:
# percent chance of rolling doubles
sum(doubles)/len(rolls) * 100

16.23

In [8]:
#2a If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# NOT three in a row. 
# 3 heads, no more, no less
n_trials = nrows = 10_000
n_coins = ncols = 8

flips = np.random.choice([True, False], size = (n_trials, n_coins))
flips

#heads = True
# tails = False

array([[False, False, False, ..., False, False, False],
       [ True,  True,  True, ..., False, False,  True],
       [ True, False, False, ..., False,  True, False],
       ...,
       [False, False, False, ...,  True,  True,  True],
       [False,  True, False, ..., False, False,  True],
       [ True,  True,  True, ..., False,  True,  True]])

In [9]:
flips_df = pd.DataFrame(flips, columns=['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8'])
flips_df.head()

f1     f2     f3     f4     f5     f6     f7     f8
0  False  False  False  False  False  False  False  False
1   True   True   True  False   True  False  False   True
2   True  False  False   True   True  False   True  False
3  False  False   True   True   True  False   True   True
4   True  False  False   True   True   True   True  False

In [10]:
(flips_df.sum(axis = 1) == 3).mean()

0.2175

In [11]:
#more than 3 heads
(flips_df.sum(axis = 1) > 3).mean()

0.6487

In [12]:
# less than 3 heads (just to check my work and make sure they add up to 1.0)
(flips_df.sum(axis = 1) < 3).mean()

0.1338

In [13]:
# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.
#    (W-W-W-D)
#    Assuming that Codeup randomly selects an alumni to put on a billboard, 
#    what are the odds that the two billboards I drive past both have data science students on them?


p_ds_students = .25
n_billboards = ncols = 2
n_simulated_students = nrows = 10**3

In [14]:
data = np.random.random(size =(nrows, ncols))
data

array([[0.978301  , 0.79029696],
       [0.89307364, 0.05069881],
       [0.85928566, 0.32280981],
       ...,
       [0.10122045, 0.2200362 ],
       [0.11097673, 0.16536726],
       [0.82198882, 0.61186632]])

In [15]:
both_ds_students = data < p_ds_students
both_ds_students

array([[False, False],
       [False,  True],
       [False, False],
       ...,
       [ True,  True],
       [ True,  True],
       [False, False]])

In [16]:
(both_ds_students.sum(axis=1) == 2).mean()

0.07

In [17]:
# 4 Poptart Problem
# Monday morning = 17 poptarts. Averge consumption rate: 3/day. STD: 1.5 
# Mon EOD: 14
# Tues EOD: 11
# Wed EOD: 8
# Thu EOD: 5
# Fri EOD: 2 what is the liklihood one of them will be mine?

poptarts = np.random.normal(3, 1.5, size=(10, 5))
poptarts_df = pd.DataFrame(poptarts, columns = ['M', 'T', 'W', 'Th', 'F'])
poptarts_df

M         T         W        Th         F
0  1.964413  1.433046  2.319327  1.794296  1.435755
1  2.240706  3.489582  3.630137  3.331864  2.498931
2  3.301183  3.867451 -0.946102  4.609741 -0.248830
3  1.679221  2.143221  4.438460  3.515642  2.654606
4  2.324847  3.508940  2.467056  1.219028  1.820149
5  4.077938  1.713429 -0.043857  1.740604  2.023534
6  4.015927  2.686295  5.318489  2.581965  5.744233
7  2.097810  3.909918  4.769957  4.970782  0.789648
8  3.837796  1.701885  3.574359  5.121088  1.683988
9  2.227728  6.096464  1.406963  4.624813  3.059143

In [18]:
# if the sum of a row >= 17, I get no poptarts on Friday. 30% chance I don't get poptarts.
(poptarts_df.sum(axis = 1) >=17).mean()

0.2

In [19]:
(poptarts_df.sum(axis = 1) <=17).mean()

0.8

In [20]:
#5. Compare heights:
#.  - Men have an average height of 178 cm and standard deviation of 8cm.
#.  - Women have a mean of 170, sd = 6cm.
#.  _ If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

men = np.random.normal(178, 8, (100))
women = np.random.normal(170, 6, (100))
men_df = pd.DataFrame(men, columns = ["men"])
women_df = pd.DataFrame(women, columns = ["women"])

In [21]:
men_df

men
0   181.869011
1   178.725610
2   175.938162
3   178.702543
4   176.822209
..         ...
95  176.590214
96  162.192443
97  179.285751
98  183.719713
99  185.541663

[100 rows x 1 columns]

In [22]:
women_df

women
0   167.703457
1   160.390693
2   172.099938
3   165.373333
4   178.903315
..         ...
95  188.005090
96  164.794834
97  174.534061
98  163.562699
99  174.715522

[100 rows x 1 columns]

In [23]:
heights_df = pd.concat([men_df, women_df], axis = 1)
heights_df

men       women
0   181.869011  167.703457
1   178.725610  160.390693
2   175.938162  172.099938
3   178.702543  165.373333
4   176.822209  178.903315
..         ...         ...
95  176.590214  188.005090
96  162.192443  164.794834
97  179.285751  174.534061
98  183.719713  163.562699
99  185.541663  174.715522

[100 rows x 2 columns]

In [24]:
heights_df.men.max()

196.49946928488873

In [25]:
heights_df['tall_women']= heights_df.men < heights_df.women


In [26]:
heights_df

men       women  tall_women
0   181.869011  167.703457       False
1   178.725610  160.390693       False
2   175.938162  172.099938       False
3   178.702543  165.373333       False
4   176.822209  178.903315        True
..         ...         ...         ...
95  176.590214  188.005090        True
96  162.192443  164.794834        True
97  179.285751  174.534061       False
98  183.719713  163.562699       False
99  185.541663  174.715522       False

[100 rows x 3 columns]

In [27]:
heights_df.tall_women.sum()

22

In [28]:
(women>men).mean()

0.22

## #6 anaconda instilation

In [29]:
# What are the odds that after having 50 students download anaconda,
#no one has an installation issue?
install = np.random.choice([0,1], size = (10000, 50), p = [249/250, 1/250])
install
(install.sum(axis = 1) == 0).mean()



0.8165

In [30]:
# probability for 100 students:
install_100 = np.random.choice([0,1], size = (10000, 100), p = [249/250, 1/250 ] )
install_100

(install_100.sum(axis = 1) == 0).mean()


0.6628

In [31]:
#probability of having an issue within 150 installs
install_150 = np.random.choice([0,1], size = (10000, 150), p = [249/250, 1/250 ] )
install_150

(install_150.sum(axis =1) > 0).mean()

0.4514

In [32]:
# probability of no issue at 450 installs
install_450 = np.random.choice([0,1], size = (10000, 450), p = [249/250, 1/250 ] )
install_450

(install_450.sum(axis=1)==0).mean()

0.1687

## #7 Food trucks at the park

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?


In [33]:
trucks = np.random.choice([0, 1], size = (10000, 3), p = [0.3, 0.7] )
trucks
(trucks.sum(axis = 1)==0).mean()

0.0273

In [35]:
# probability that a truck will show up this week:
trucks_this_week = np.random.choice([0,1], size = (1000, 7), p = [0.3, 0.7])
trucks_this_week

(trucks_this_week.sum(axis=1)>=1).mean()

1.0

## #8 shared birthdays

In [36]:
# odds if there are 23 people in a room
bd = np.random.choice(range(1,366), size = (10000, 23))
bd

pd.DataFrame(bd).nunique(axis = 1)

(pd.DataFrame(bd).nunique(axis = 1) < 23).mean()

0.5158

In [39]:
# probabilty when 20 people
bd = np.random.choice(range(1,366), size = (10000, 20))
bd

pd.DataFrame(bd).nunique(axis = 1)

(pd.DataFrame(bd).nunique(axis = 1) < 20).mean()

0.4132

In [38]:
# probabiity when 40 people:
bd = np.random.choice(range(1,366), size = (10000, 40))
bd

pd.DataFrame(bd).nunique(axis = 1)

(pd.DataFrame(bd).nunique(axis = 1) < 40).mean()

0.8921